version: 2

env:
  - GO111MODULE=on

project_name: misha

before:
  hooks:
    - go mod tidy
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    main: ./cmd/misha

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "Misha {{.Version}}"

homebrew_casks:
  - repository:
      owner: misha-ssh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: misha
    commit_author:
      name: deniskorbakov
      email: korbakovd009@gmail.com
    commit_msg_template: "Brew update for {{ .ProjectName }} version {{ .Tag }}"
    description: "misha - ssh connection manager"
    license: "MIT"
    manpages:
      - "manpages/misha.1.gz"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/misha"]
          end