version: 2
project_name: misha
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    main: ./cmd/misha

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "Misha ssh {{.Version}}"

homebrew_casks:
  -
    name: misha
    commit_author:
      name: deniskorbakov
      email: korbakovd009@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "misha - ssh connection manager"
    license: "MIT"
    install: |
      bin.install "misha"
    test: |
      system "#{bin}/misha --version"
    # Repository to push the generated files to.
    repository:
      owner: misha-ssh
      name: homebrew-misha
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"