# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2
variables:
  main: "./cmd/misha"
  binary_name: "misha"

env:
  - GO111MODULE=on

project_name: misha

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run {{ with .Var.main }}{{ . }}{{ else }}.{{ end }} completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run {{ with .Var.main }}{{ . }}{{ else }}.{{ end }} completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run {{ with .Var.main }}{{ . }}{{ else }}.{{ end }} completion "fish" >./completions/{{ .ProjectName }}.fish'
    - sh -c 'go run {{ with .Var.main }}{{ . }}{{ else }}.{{ end }} man | gzip -c >./manpages/{{ .ProjectName }}.1.gz'

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
    main: ./cmd/misha

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "Misha {{.Version}}"

homebrew_casks:
  - repository:
      owner: misha-ssh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: misha
    commit_author:
      name: deniskorbakov
      email: korbakovd009@gmail.com
    commit_msg_template: "Brew update for {{ .ProjectName }} version {{ .Tag }}"
    description: "misha - ssh connection manager"
    license: "MIT"
    manpages:
      - "manpages/misha.1.gz"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/misha"]
          end

brews:
  - repository:
      owner: misha-ssh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: deniskorbakov
      email: korbakovd009@gmail.com
    install: |-
      bin.install "{{ with .Var.binary_name }}{{ . }}{{ else }}{{ .ProjectName }}{{ end }}"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
      man1.install "manpages/{{ .ProjectName }}.1.gz"

nfpms:
  - package_name: misha
    file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://misha-ssh.github.io/docs
    description: |-
      Misha - ssh connection manager
    maintainer: Denis Korbakov <korbakovd009@gmail.com>
    license: MIT
    vendor: MishaSSH
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    overrides:
      deb:
        suggests:
          - ssh
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package